language: python
python:
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- pip install -r requirements-tests.txt
- python -m pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: 1XV0rWtNBM1X03R0eEZEbIqPwGM4Uof5AZnf/RrYfa9pyVLW+bOpzmNxAnsjkhVWOH5ETejtJl7Nlqiw99zQfbUBzdArgPi4SqVRY9/y3Ga5cs0Xn2b6QniD0VAD/kTUu0IFaA5Lm34TNmWeQxAP1sblYvBc181zuB1EMbV7tEna4dVIO1+bdF5+nLhHY3kXj2zbBe2x28AEKsyHFr+yePE3YKr0j1ZirjgfWj3qkA8caDk38QIc40FT4mcKWajhj1au10OLFLKEJwi8yireVjls5WBktzInmwSCmdESf22/8UqUWAvbuWagufOwbRs4V5g8Mg3R20NEMN3Gvq1cSe0FkeoPYtZ5hvMlMid4QL8M/7iqOS4/NIVePGhb3Gnc7HY06PJu7Dlpqe0htd/vpCYYHrkc8fgBiMk0dJtAvPxk/vOQZGhv9F7JMBWi57nmxbZWMuJmW+4Yc8U0Pha5G6+DtgDjkx36/b7I9pyX13WB5vs63NCPJRd3H/lfEVEPfNaXpENpWDED0hyeWCTv+XDz6jvNDDBH6WpV81UK1JU523lzYQAir207LnyYI49PKkf4DeiOGZ6nx1uHlma2ceADFalJGK9te3SZM02SebAqAOC541JM9aZUpt2YPhKG2Xh4pFippetN95QdHoBEaCvzq+FRimEKSZaX4JEksiE=
  on:
    tags: true
